### PR TITLE
Migrated to typescript

### PR DESCRIPTION
**Pull request by andysham**
I felt like this needed to be in typescript for some reason

I used snippets of your code in a personal project because I needed access to the `tls.Server` object you were using internally, and in the process gave everything explicit types

Up to you whether you want to merge it or not

### CODE REVIEW

**Comment by lodenrogue** [comment]
Will this affect projects that are only using JS and not typescript?

**Comment by andysham** [comment]
The only change (I believe) should be
```javascript
const gemini = require('gemini-server')
...
const app = gemini(options)
```
becoming
```javascript
const gemini = require('gemini-server')
...
const app = gemini.createServer(options)
```

There's probably some way of not forcing that but I've not got the time to dwell on it right now, apart from that and some other minor style changes everything should be exactly the same

I've also commented out `gemini.static` for now as the keyword `static` is throwing issues with the compiler and it doesn't seem to be implemented just yet anyways

**Comment by lodenrogue** [comment]
I'm not familiar with TypeScript. Are you saying your changes will be 100% compatible with the existing JavaScript code? No changes for the end user who doesn't want to use TypeScript?

**Comment by jgkaplan** [comment]
it might be best to add them to the @types repo to allow people to install it only if they want.
https://github.com/DefinitelyTyped/DefinitelyTyped
I think this is how express and a lot of other frameworks do it.

**Comment by jgkaplan** [comment]
on an unrelated note, does anyone have an idea for a better name for this than geminiServer

**Comment by jgkaplan** [comment]
I'm trying to add typescript .d.ts files, but I haven't used typescript and I'm not super sure how to test them. For now, I'm pushing them to the types branch.

**Pull request closed without merging**
